# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f69d15ba79c263b948e35cb53ace6bfd25e30670a741f987d6a4df67be055de548e835f4e019dd6f371f26c1a94f52d36c446ec803b4be9fc123cb4b25d1e7

test:
  secret_key_base: bb91bcbe3eb7964e444f94c351e01b82ddd2e9c0f469150c4311cbf4a8c6c376bba9d419291f9ad62fe46a738abc63f3704d11035daafcdd2e399de4d85e225d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
